### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by BrainPotter** [sachinpuranik99/AOD_Net#2]
When I ran the code,I faced the following error:
AssertionError                            Traceback (most recent call last)
<ipython-input-7-5857a9f5b13a> in <module>()
     15 print ("Train set size is:", train_set_size, ",", "Steps per epochs is:", steps_per_epoch, ",", "batch size is:", batch_size, "total epochs is:", epochs)
     16 #assert (train_set_size == (steps_per_epoch*batch_size))
---> 17 assert (train_set_size == (len(glob.glob(train_label_dir+'/'+'*.png'))))
     18 
     19 

AssertionError:
my OS is ubuntu 16.04 , python 3.6 ,anaconda 3.5.1.0 
Please help me to fix,thank you very much!

**Comment by sachinpuranik99** [comment]
The assertion checks if the number of training (hazy) images is the same as the number of labels (clear) images. 
There is some mismatch in your case. 

If it is because of some valid reason, say many hazy images correspond to a single clear image, then you can comment out the assertion.

Let me know if you still face some issues.

**Comment by BrainPotter** [comment]
When I download your source on the google,I found that there was nothing in dark-channel-prior-dehazing/img. When modified the  AssertionError mentioned before,I faced another error:
IndexError                                Traceback (most recent call last)
<ipython-input-29-9f5f187c970d> in <module>()
      6 #     print(Y_train.shape)
      7 
----> 8 print(X_test[0].shape)
      9 print(X_test.shape)
     10 

IndexError: index 0 is out of bounds for axis 0 with size 0
And I found you mentioned your database named TAMU,could you share this to me.My email address is junnian_L@163.com 
Thank you very much!

**Comment by sachinpuranik99** [comment]
> When I download your source on the google,I found that there was nothing in dark-channel-prior-dehazing/img


The data size was too big to be uploaded on the drive, hence it was not uploaded. To generate the images you need to pass the hazy images through a dark channel prior algorithm

> And I found you mentioned your database named TAMU,could you share this to me.


You can find the dataset here. 
https://sites.google.com/view/reside-dehaze-datasets/reside-standard?authuser=0

> IndexError Traceback (most recent call last)
> in ()
> 6 # print(Y_train.shape)
> 7
> ----> 8 print(X_test[0].shape)
> 

This is a basic python error saying X_test array is empty. Make sure you have parsed the data correctly.
