### ISSUE TITLE
sorry to bother you

### ISSUE THREAD

**Issue by gao-ziqi** [sachinpuranik99/AOD_Net#3]
Can you explain what training data set you are using? I am very grateful to you.

**Comment by sachinpuranik99** [comment]
I used the RESIDE dataset from this [paper](https://arxiv.org/pdf/1712.04143.pdf). 

The dataset can be found [here.](https://sites.google.com/view/reside-dehaze-datasets/reside-standard?authuser=0)

**Comment by gao-ziqi** [comment]
Thank you for your kindness ,I am a DL beginner,and could you please teach me how to put the pictures in the right place?
Is it right to put clear and foggy pictures in two folders as 'train_data_dir' and 'train_label_dir'?
Really thanks for you.

**Comment by sachinpuranik99** [comment]
> Is it right to put clear and foggy pictures in two folders as 'train_data_dir' and 'train_label_dir'?

That's correct.

**Comment by gao-ziqi** [comment]
OK.^_^
